#!/bin/bash

# Script to run a command within the Docker container.
#
# Usage: docker-run [port] command
# If no port is given the default port is used.

DEFAULT_PORT=3001

case $1 in
    ''|*[!0-9]*) PORT=$DEFAULT_PORT; ARGS="$@" ;;
    *) PORT="$1"; echo "$@"; ARGS="${@:2}" ;;
esac

docker run -it --rm -v $(pwd):/home/aviator/aviator -p $PORT:$PORT aviator $ARGS
