# -*- mode: ruby -*-
# vi: set ft=ruby :

# Note: Need to run `sudo systemctl start clusterware-configurator` after the
# VM is created to configure.

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "hfm4/centos7"
  config.vm.box_check_update = false
  config.vm.hostname = "master"

  # Update the below vars to match your configuration
  clusterware_root = "#{ENV['HOME']}/projects/alces/clusterware-project"
  access_manager_root = "#{ENV['HOME']}/projects/alces/access-manager-project"
  hostonly_net = "vboxnet0"

  config.vm.provider "virtualbox" do |v|
    v.gui = true
    v.customize ["modifyvm", :id, "--nic2", "hostonly"]
    v.customize ["modifyvm", :id, "--hostonlyadapter2", hostonly_net]
  end

  provision_script = <<-RUBY
  export alces_SOURCE_DIR=/media/host/clusterware
  export alces_OS=el7
  export alces_DISABLE_SPINNER=true
  export alces_BUILD_TMP=tmp/simple-el7
  #export alces_NAMING_auth="GNjdioBB+c6r2Dkackqt"
  #export cw_HANDLER_DEFAULT_REPO_URL=/media/host/clusterware-handlers
  #export cw_SESSION_DEFAULT_REPO_URL=/media/host/clusterware-sessions
  #export cw_SERVICEWARE_DEFAULT_REPO_URL=/media/host/clusterware-services
  #export cw_STORAGE_DEFAULT_REPO_URL=/media/host/clusterware-storage
  /media/host/clusterware/scripts/bootstrap
  cp /vagrant/config.yml /opt/clusterware/etc/config.yml
  PATH=/opt/clusterware/bin:$PATH
  alces handler enable clusterable
  alces handler enable cluster-gridware
  alces handler enable cluster-nfs
  alces handler enable cluster-sge
  alces handler enable taskable
  alces handler enable cluster-appliances
  RUBY
  config.vm.provision 'shell', inline: provision_script

  config.vm.synced_folder "#{clusterware_root}/clusterware", "/media/host/clusterware"
  #config.vm.synced_folder "#{clusterware_root}/metalware", "/media/host/metalware"
  #config.vm.synced_folder "#{clusterware_root}/clusterware-handlers", "/media/host/clusterware-handlers"
  #config.vm.synced_folder "#{clusterware_root}/clusterware-sessions", "/media/host/clusterware-sessions"
  #config.vm.synced_folder "#{clusterware_root}/clusterware-services", "/media/host/clusterware-services"
  #config.vm.synced_folder "#{clusterware_root}/clusterware-storage", "/media/host/clusterware-storage"
  #config.vm.synced_folder "#{clusterware_root}/packager-base", "/media/host/clusterware-packages"


  # AAM additions to Clusterware Vagrantfile below this point.

  # Sync in AAM daemon.
  config.vm.synced_folder "#{access_manager_root}/../access-manager-project/alces-access-manager-daemon", "/media/host/alces-access-manager-daemon"

  # Refer to
  # `https://github.com/alces-software/alces-access-manager-daemon`
  # for information on running the daemon.
end
