cluster:
  uuid: '7b4249e8-637a-11e5-a343-7831c1c0e63c'
  token: '8R0c6lyMG1pJGP/wzg8dHA=='
  name: 'el7cluster'
  role: 'master'
  tags:
    scheduler_roles: ':master:compute:'
    galaxy_roles: ':master:compute:'
    storage_roles: ':master:'
  interface: enp0s8
  quorum: 2
  service_url: https://flight.alces-software.com
instance:
  users:
  - username: bob
    uid: 509
    group: bob
    gid: 509
    groups:
      - gridware
      - admins:388
    ssh_public_key: |
      ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC3kt62iiuaHzLXfnQ2pkYrjDKSsUFFwiI0uJtOu97/ENRsL5cSKsJhJDrrmwxx46rRExAzKMFE+4TMreKciS9w7W7HZ3OiuwSP9gis6T8G9Ml6mEVoX1mVBp953r5v3DUTnL5o9pEgKCB7dI2lV+znBbE0/Ij6Feh2ossBZTiMKIQX/apN5dmw7CH+PON78IKuSUBvNpyjwHE0N5sdtyR4bFVtsWDX9mCSoHLc4I0NeSLIw+NjnPTJF2KpxgcU6rwmRqt7LaAiVrj//7EId1Kyv/A1n2Q3fDtbkiZflXBq9aDoWiVsIHT8DlG1TgITDSWgqa/15rOvwyp2nOo3MPfJ bob@bob-alces
