# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "hfm4/centos7"
  config.vm.box_check_update = false
  config.vm.hostname = "master-#{(rand * (10 ** 8)).to_i.to_s(16)}.cluster"

  # Update the below vars to match your configuration
  #projects = "#{ENV['HOME']}/projects"
  projects = "#{ENV['HOME']}/projects/alces"
  hostonly_net = "vboxnet0"

  config.vm.provider "virtualbox" do |v|
    v.gui = true
    v.customize ["modifyvm", :id, "--nic2", "hostonly"]
    v.customize ["modifyvm", :id, "--hostonlyadapter2", hostonly_net]
  end

  provision_script = <<-RUBY
  export alces_SOURCE_DIR=/media/host/clusterware
  export alces_OS=el7
  export alces_DISABLE_SPINNER=true
  export alces_BUILD_TMP=tmp/simple-el7
  #export alces_NAMING_auth="GNjdioBB+c6r2Dkackqt"
  #export cw_HANDLER_DEFAULT_REPO_URL=/media/host/clusterware-handlers
  #export cw_SESSION_DEFAULT_REPO_URL=/media/host/clusterware-sessions
  #export cw_SERVICEWARE_DEFAULT_REPO_URL=/media/host/clusterware-services
  #export cw_STORAGE_DEFAULT_REPO_URL=/media/host/clusterware-storage
  /media/host/clusterware/scripts/bootstrap
  cp /vagrant/config.yml /opt/clusterware/etc/config.yml
  PATH=/opt/clusterware/bin:$PATH
  alces handler enable clusterable
  alces handler enable cluster-gridware
  alces handler enable cluster-nfs
  alces handler enable cluster-sge
  alces handler enable taskable
  alces handler enable cluster-appliances
  RUBY
  config.vm.provision 'shell', inline: provision_script

  config.vm.synced_folder "#{projects}/clusterware", "/media/host/clusterware"
  #config.vm.synced_folder "#{projects}/metalware", "/media/host/metalware"
  #config.vm.synced_folder "#{projects}/clusterware-handlers", "/media/host/clusterware-handlers"
  #config.vm.synced_folder "#{projects}/clusterware-sessions", "/media/host/clusterware-sessions"
  #config.vm.synced_folder "#{projects}/clusterware-services", "/media/host/clusterware-services"
  #config.vm.synced_folder "#{projects}/clusterware-storage", "/media/host/clusterware-storage"
  #config.vm.synced_folder "#{projects}/packager-base", "/media/host/clusterware-packages"


  # AAM additions to Clusterware Vagrantfile below this point.

  # Sync in ASM daemon to test authing.
  # TODO: change this to AAM daemon when this exists.
  config.vm.synced_folder "#{projects}/alces-storage-manager-daemon", "/media/host/alces-storage-manager-daemon"

  # TODO: various setup needed to make ASM daemon run initially - installing
  # gems, ruby headers, git etc - make this part of provisioning process.

  # Start ASM daemon in screen session.
  config.vm.provision 'shell',
    run: 'always',
    inline: "cd /media/host/alces-storage-manager-daemon && screen -S asmd -d -m bin/alces-storage-manager-daemon"

  # Note: to forward daemon port use:
  # ssh -L 25269:10.0.2.15:25269 -p 2222 vagrant@localhost
end
