---
:auth:
  # The ASM daemon used for authentication.
  :address: "127.0.0.1:25268"
  :ssl: true
:ssl:
  # Options used for SSL connections
  :root: /home/bob/projects/alces/alces-storage-manager-daemon/config/ssl
  :certificate: daemon_crt.pem
  :key: daemon_key.pem
  :ca: alces-ca_crt.pem
