---
clusters:
  - name: Clusterware Vagrant
    ip: 127.0.0.1
    auth_port: 25269
    ssl: true
    ssl_connection:
      # Options used for SSL connections
      root: /home/bob/projects/alces/alces-access-manager-daemon/config/ssl
      certificate: daemon_crt.pem
      key: daemon_key.pem
      ca: alces-ca_crt.pem
    timeout: 5
  - name: Another Cluster
    ip: 10.10.10.10
    auth_port: 25269
    ssl: false
    timeout: 5

environment:
  name: Bob's Cluster
...
