---
clusters:
  - name: Clusterware Vagrant
    ip: 127.0.0.1
    auth_port: 25269
    ssl: true
  - name: Another Cluster
    ip: 10.10.10.10
    auth_port: 25269
    ssl: false

environment:
  name: Bob's Cluster

ssl:
  # Options used for SSL connections
  root: /home/bob/projects/alces/alces-access-manager-daemon/config/ssl
  certificate: daemon_crt.pem
  key: daemon_key.pem
  ca: alces-ca_crt.pem

timeout: 30
...
