source 'https://rubygems.org'


gem 'rails', '4.2.5'

gem 'rails-api'

gem 'spring', :group => :development

gem 'puma'

group :test do
  gem 'mocha'
  gem 'minitest-reporters'
end

# Required for daemon client.
gem 'net-ping'
gem 'alces-tools', :github => 'alces-software/alces-tools', :tag => '0.13.0'


# To use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the app server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano', :group => :development

# To use debugger
# gem 'ruby-debug19', :require => 'ruby-debug'
